import { cva } from "class-variance-authority";

export const typographyVariants = cva('', {
  variants: {
    variant: {
      h1: 'text-5xl font-bold tracking-tight leading-tight md:text-6xl lg:text-7xl',
      h2: 'text-3xl font-bold tracking-tight leading-tight md:text-4xl lg:text-5xl',
      h3: 'text-2xl font-bold tracking-tight leading-snug md:text-3xl lg:text-4xl',
      h4: 'text-xl font-semibold tracking-tight leading-snug md:text-2xl lg:text-3xl',
      h5: 'text-lg font-semibold tracking-tight leading-snug md:text-xl lg:text-2xl',
      h6: 'text-base font-semibold tracking-tight leading-snug md:text-lg lg:text-xl',
      p: 'text-base leading-relaxed font-normal md:text-lg',
      span: 'text-base font-normal',
      small: 'text-sm font-normal leading-relaxed',
      lead: 'text-xl leading-relaxed font-light md:text-2xl',
      blockquote: 'border-l-4 border-primary pl-4 italic text-muted-foreground',
      code: 'relative rounded bg-muted px-[0.3rem] py-[0.2rem] font-mono text-sm font-semibold',
      pre: 'overflow-x-auto rounded-lg bg-muted p-4 font-mono text-sm',
      label: 'text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70',
    },
    size: {
      xxs:'text-xs md:text-sm',
      xs: 'text-xs md:text-sm lg:text-base',
      sm: 'text-sm md:text-base lg:text-lg',
      base: 'text-base md:text-lg lg:text-xl',
      lg: 'text-lg md:text-xl lg:text-2xl',
      xl: 'text-xl md:text-2xl lg:text-3xl',
      '2xl': 'text-2xl md:text-3xl lg:text-4xl',
      '3xl': 'text-3xl md:text-4xl lg:text-5xl',
      '4xl': 'text-4xl md:text-5xl lg:text-6xl',
      '5xl': 'text-5xl md:text-6xl lg:text-7xl',
      '6xl': 'text-6xl md:text-7xl lg:text-8xl',
      '7xl': 'text-7xl md:text-8xl lg:text-9xl',
      '8xl': 'text-8xl md:text-9xl lg:text-10xl',
    },
    weight: {
      thin: 'font-thin',
      extralight: 'font-extralight',
      light: 'font-light',
      normal: 'font-normal',
      medium: 'font-medium',
      semibold: 'font-semibold',
      bold: 'font-bold',
      extrabold: 'font-extrabold',
    },
    color: {
      default: 'text-foreground',
      muted: 'text-muted-foreground',
      primary: 'text-primary',
      secondary: 'text-secondary-foreground',
      accent: 'text-accent-foreground',
      destructive: 'text-destructive',
      card: 'text-card-foreground',
      popover: 'text-popover-foreground',
      white: 'text-white',
      inherit:''
    },
    align: {
      left: 'text-left',
      center: 'text-center',
      right: 'text-right',
      justify: 'text-justify',
    },
    transform: {
      none: 'normal-case',
      uppercase: 'uppercase',
      lowercase: 'lowercase',
      capitalize: 'capitalize',
    },
  },
  defaultVariants: {
    variant: 'p',
    color: 'default',
    align: 'left',
    transform: 'none',
  },
})
